backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "institution"
    label: "Institución"
    folder: "site/content/institutions"
    create: true
    extension: "json"
    fields:
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Sector", name: "sector", widget: "string" }
      - { label: "Descripcion", name: "descripcion", widget: "text" }
      - { label: "Mision", name: "mision", widget: "text" }
      - { label: "Vision", name: "vision", widget: "text" }
      - { label: "Correo", name: "correo", widget: "string" }
      - { label: "Telefono", name: "telefono", widget: "number" }
      - { label: "Facebook", name: "fb", widget: "string" }
      - { label: "Twitter", name: "tw", widget: "string" }
      - { label: "Foto", name: "fotoURL", widget: "string" }
  - name: "candidate" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Candidate" # Used in the UI, ie.: "New Post"
    folder: "site/content/candidates" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: "json"
    fields: # The fields each document in this collection have
      - { label: "Nombre", name: "nombre", widget: "string" }
      - { label: "Sexo", name: "sexo", widget: "string" }
      - { label: "Puesto", name: "puesto", widget: "string" }
      - { label: "Dependencia", name: "dependencia", widget: "string" }
      - { label: "Departamento", name: "departamento", widget: "string" }
      - { label: "Institution", name: "institution", widget: "string" }
      - { label: "Seleccionar institución", name: "seleccionarInstitución", widget: "string" }
      - { label: "Election", name: "election", widget: "string" }
      - { label: "Seleccionar elección", name: "seleccionarElección", widget: "string" }
      - { label: "Comission", name: "comission", widget: "string" }
      - { label: "Seleccionar comisión", name: "seleccionarComisión", widget: "string" }
      - { label: "Fechalaboral", name: "fechalaboral", widget: "string" }
      - { label: "Nocolegiado", name: "nocolegiado", widget: "string" }
      - { label: "Estadocivil", name: "estadocivil", widget: "string" }
      - { label: "Profesion", name: "profesion", widget: "string" }
      - { label: "Anosexperiencia", name: "anosexperiencia", widget: "string" }
      - { label: "Experiencia profesional", name: "experienciaProfesional", widget: "string" }
      - { label: "Experiencia academica", name: "experienciaAcademica", widget: "string" }
      - { label: "Publicaciones", name: "publicaciones", widget: "string" }
      - { label: "Foto", name: "fotoURL", widget: "image", required: false }
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
